### PR TITLE
New authentication system

### PR DESCRIPTION
**Pull request by FireMario211**
This PR adds a new authentication system to Amethyst Host. While there currently isn't a way to authenticate with third parties such as **Discord** or **GitHub**. Users will be able to create an account and authenticate with the account.

This PR also fixes bugs and fixes vulnerabilities, and adds new additions.

The bugs fixed are:
- When going to `https://amethyst.host/api/anything`, it'll show an error `TypeError: Cannot read property 'prop' of undefined` with an error stack.

The vulnerabilities fixed are:
- The addition of the module `helmet` (Prevents XSS, iframe Protection, and more)

The new additions are:
- register.ts - Creates an account for a user
- New .env options (`SALT`, `ACCESS_TOKEN`)
- Added new modules: `better-sqlite3`, `argon2`, `body-parser`, `cookie-parser`, `helmet`, `jsonwebtoken`, `ms`
- auth.ts - Allows a user to "login"
- sql.ts - Allows use of the SQLite DB.

If there are any suggestions to change in this PR, let me know and I'll try fixing them.

**There should not be any errors**
I've tested this on my local machine and have found no errors when testing this.

### CODE REVIEW

**Comment by Em1tt** [comment]
Love this. Will test soon

**Comment by FireMario211** [comment]
Not sure why the checks are saying the modules don't exist when I put them in `package.json`

**Comment by Em1tt** [comment]
It looks like you need to add the packages into package-lock.json aswell to fix the check

**Comment by b1tt0** [comment]
@FireMario211 you have to do `npm ci` in order to make npm do that, i guess

**Comment by FireMario211** [comment]
Made another commit which I believe fixes the checking issue as it adds the modules in package-lock.json

**Comment by Em1tt** [comment]
Please fix the conflicting files and we can do a merger with the main branch

**Comment by Em1tt** [comment]
Resolved the conflicts, checks have now passed. Merging into main.

**Pull request merged**
